# Generated by Django 5.1.7 on 2025-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
